services:
  service-pg:
    image: bitnami/postgresql
    ports:
      - '5433:5432' # 5432 já é usado pelo postgres local
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=connect

  service-redis:
    image: bitnami/redis
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      